### ISSUE TITLE
Force usernames being unique

### ISSUE THREAD

**Issue by infernostars** [KUKHUA/txttunnel#1]
Currently, there can be overlapping usernames. This is fine, but it leads to cases of impersonation - perhaps there should be an ID instead [and users can have nicknames]? Preferably IDs would also be persistent [would allow for bans and stuff like that] but that's hard without an actual account system and nobody likes account systems

**Comment by infernostars** [comment]
actually this is a client issue apparently [although maybe the API should have autogen'd IDs? would be useful]

**Comment by KUKHUA** [comment]
This code is very hacky (wasn't even intended for chat), I think the slop website should use something else. I would say have a login with Github thing.
